Elsie_Final/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path
from products import views as product_views
from carts import views as cart_views
from orders import views as order_views
from accounts import views as accounts_views
from marketing import views as marketing_views


urlpatterns = [

    path('admin/', admin.site.urls),
    path('accounts/logout/', accounts_views.LogOutView, name='auth_logout'),
    path('accounts/login/', accounts_views.LogInView, name='auth_login'),
    path('accounts/register/', accounts_views.RegisterView, name='auth_register'),
    path('accounts/address/add/', accounts_views.AddUserAddress, name='add-user-address'),
    path('', product_views.home, name='home'),
    path('s/', product_views.search, name='search'),
    path('items/', product_views.all, name='items'),
    path('cart/', cart_views.ViewCart, name='cart'),
    path('checkout/', order_views.Checkout, name='checkout'),
    path('orders/', order_views.Orders, name='user-orders'),
    
    path('cart/<id>\d+/$', cart_views.RemoveFromCart, name='remove-from-cart'),
    path('cart/<slug:slug>/', cart_views.AddToCart, name='add-to-cart'),
    path('items/<slug:slug>/', product_views.single, name='single-item'),
    path('accounts/activate/<str:activation_key>', accounts_views.ActivationView, name='activate'),
    path('ajax/dismiss_marketing_message/', marketing_views.DismissMarketingMessage, name='dismiss-marketing-message'),
    path('ajax/email_signup/', marketing_views.EmailSignUp, name='ajax_email_signup'),
    path('ajax/add-user-address/', accounts_views.AddUserAddress, name='ajax-add-user-address'),


    #(?P<all_items>.*)
    #(?P<all_items>\d+)
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.urls import reverse
from django.db import models
from django.db.models.signals import post_save  

# Create your models here.

class Category(models.Model):
	title = models.CharField(max_length=120)
	description = models.TextField(null=True, blank=True)
	slug = models.SlugField(unique=True)
	created = models.DateTimeField(auto_now_add=True, auto_now=False)
	updated = models.DateTimeField(auto_now_add=False, auto_now=True)
	featured = models.BooleanField(default=None)
	active = models.BooleanField(default=True)


	def __str__(self):
		return self.title


	
class Item(models.Model):
	title = models.CharField(max_length=100)
	description = models.TextField(null=True, blank=True)
	category = models.ManyToManyField(Category,null=True, blank=True)
	price = models.DecimalField(max_digits=100, decimal_places=2, default=0.00)
	sale_price = models.FloatField(null=True, blank=True)
	slug = models.SlugField(unique=True)
	created = models.DateTimeField(auto_now_add=True, auto_now=False)
	updated = models.DateTimeField(auto_now_add=False, auto_now=True)
	active = models.BooleanField(default=True)
	update_defaults = models.BooleanField(default=False)


	def __str__(self):
		return self.title


	class meta:
		unique_together = ('title', 'slug')

	def get_price(self):
		return self.price


	def get_absolute_url(self):
		return reverse('single-item', kwargs={'slug': self.slug })



class ItemImage(models.Model):
	item = models.ForeignKey(Item, on_delete=models.CASCADE)
	image = models.ImageField(upload_to='products/images/')
	featured = models.BooleanField(default=False)
	thumbnail = models.BooleanField(default=False)
	active = models.BooleanField(default=True)
	updated = models.DateTimeField(auto_now_add=False, auto_now=True)



	def __str__(self):
		return self.item.title


class VariationManager(models.Manager):

	def all(self):
		return super(VariationManager,self).filter(active=True)

	def sizes(self):
		return self.all().filter(category='size')

	def colors(self):
		return self.all().filter(category='color')

	def packages(self):
		return self.all().filter(category='package')

VAR_CATEGORIES = (
	('size','size'),
	('color', 'color'),
	('package', 'package'),
)

class Variation(models.Model):
	item = models.ForeignKey(Item, on_delete=models.CASCADE)
	category = models.CharField(max_length=120, choices=VAR_CATEGORIES, default='size')
	image = models.ForeignKey(ItemImage, null=True, blank=True, on_delete=models.CASCADE)
	title = models.CharField(max_length=100)
	price = models.DecimalField(max_digits=100, decimal_places=2, null=True, blank=True)
	active = models.BooleanField(default=True)
	updated = models.DateTimeField(auto_now_add=False, auto_now=True)

	objects = VariationManager()
	

	def __str__(self):
		return self.title



# T-shirt 5
# Active Wear 6

def item_defaults(sender, instance, created, *args, **kwargs):
	if instance.update_defaults:
		categories = instance.category.all()
		print(categories)
		for cat in categories: 
			print(cat.id)
			if cat.id == 5:#id for tshirt #----> create function for handling all category ids
				small_size = Variation.objects.get_or_create(item=instance,category='size',title='Small')
				medium_size = Variation.objects.get_or_create(item=instance,category='size',title='Medium')
				large_size = Variation.objects.get_or_create(item=instance,category='size',title='Large')


		instance.update_defaults = False
		instance.save()


post_save.connect(item_defaults, sender=Item)

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from .models import UserAddress


User = get_user_model()

class UserAddressForm(forms.ModelForm):
	default = forms.BooleanField(label='Make default')
	class Meta:
		model = UserAddress
		fields = [
		'address',
		'address2',
		'country',
		'zip_code',
		'county',
		'town',
		'phone',
	]


class LogInForm(forms.Form):
	username = forms.CharField()
	password = forms.CharField(widget=forms.PasswordInput())

	def clean_username(self):
		username = self.cleaned_data.get('username')
		try:
			user = User.objects.get(username=username)
		except User.DoesNotExist:
			raise forms.ValidationError('User not found! Are you sure you are registered?Please go ahead and create an account')
		return username

	def clean_password(self):
		username = self.cleaned_data.get('username')
		password = self.cleaned_data.get('password')
		try:
			user = User.objects.get(username=username)
		except:
			user = None
		if user is not None and not user.check_password(password):
			raise forms.ValidationError('Invalid password! Please try again')
		elif user is None:
			pass
		else:
			return password


class RegistrationForm(forms.ModelForm):
	email = forms.EmailField(label='Email')
	password1 = forms.CharField(label='Set Password', widget=forms.PasswordInput())
	password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput())

	class Meta:
		model = User
		fields = ['username','email']

	def clean_password2(self):
		password1 = self.cleaned_data.get('password1')
		password2 = self.cleaned_data.get('password2')
		if password1 and password2 and password1 != password2:
			raise forms.ValidationError('Passwords do not match')
		return password2

	def clean_email(self):
		email = self.cleaned_data.get('email')
		email_count = User.objects.filter(email=email).count()
		if email_count > 0:
			raise forms.ValidationError('This email is already registered, Please check and try again or reset your password')
		return email

	def save(self, commit=True):
		user = super(RegistrationForm, self).save(commit=False)
		user.set_password(self.cleaned_data['password1'])
		if commit:
			user.save()
		return user





	
		

products/views.py
from django.shortcuts import render
from . models import Item, ItemImage
from django.http import Http404
from marketing.models import MarketingMessage, Slider
# Create your views here.



def search(request):
	try:
	    q = request.GET.get('q')
	except:
		q = None
	if q:
		items = Item.objects.filter(title__icontains=q)
		context = {"query": q, "items": items}
		template = 'results.html'
	else:
		template = 'home.html'
		context={}
	
	return render(request, template, context)



def home(request):
	sliders = Slider.objects.all_featured()
	items = Item.objects.all()
	marketing_message = MarketingMessage.objects.all()[0]
	context={'items': items,
			'marketing_message':marketing_message,
			'sliders': sliders
			}
	return render(request, 'home.html', context)



def all(request):
	items = Item.objects.all()
	context={'items': items }

	return render(request, 'all.html', context)


def single(request, slug):
	try:
		item = Item.objects.get(slug=slug)
		# images = item.itemimage_set.all()
		images = ItemImage.objects.filter(item=item)
		context={'item': item, 'images': images }

		return render(request, 'single.html', context)
	except:
		raise Http404

templates/products/activation-complete.html
{% extends 'base.html' %}
{% block content %}

<h1>{{page_message}}</h1>


{% endblock %}

templates/products/all.html
{% extends 'base.html' %}
{% load static %}

{% block head_title  %}
  Products ||

{% endblock %}

{% block styles %}

 .jumbotron{

 /*color: red;*/
}

{% endblock %}



{% block content %}
<div class="row">
  
	
    {% for item in items %}
          <div class="thumbnails">
            {% if item.itemimage_set %}
                  {% for item in item.itemimage_set.all %}
                  <div class='col-sm-2'>  
                      {% if item.featured %}
                      <div style="width:150px;height:150px;/*background-color: red;*/background-image:url('{{ MEDIA_URL }}{{ item.image.url }}');background-repeat: no-repeat; background-size: cover; background-position: center; margin: 0 auto;">
                      </div>
                      <!-- <img class="img-responsive" src="{{ MEDIA_URL }}{{ item.image.url }}"/> -->
                      {% endif %}
                  {% endfor %}
            {% else %}
            <img class="img-responsive" src="{% static 'img/placeholder.svg' %}"/>
            {% endif %}
                <div class="caption">
                  <a href="/items/{{ item.slug }}"><h3>{{ item.title }}</h3></a>
                  <p>{{ item.description|truncatechars:500 }}</p>
                  <p><a href="/items/{{ item.slug }}" class="btn btn-primary" role="button">View</a><a href="#" class="btn btn-default" role="button">Button</a></p>
                </div>
          </div>
      
  </div>
    {% cycle "" "" "" "" "" "</div><br/><hr/><div class='row'>" %}

    {% endfor %}
  
</div>
{% endblock %}

templates/products/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">
    <link rel="canonical" href="https://getbootstrap.com/docs/3.3/examples/navbar-static-top/">

    <title>Elsie Collections</title>


    {% load static %}

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}"/>

    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
<!-- Optional theme -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css" integrity="sha384-6pzBo3FDv/PJ8r2KRkGHifhEocL+1X2rVCTTkUfGk7/0pbek5mMa1upzvWbrUbOZ" crossorigin="anonymous">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="https://getbootstrap.com/docs/3.3/assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/3.3/examples/navbar-static-top/navbar-static-top.css" rel="stylesheet">

    <style>

      .alert-top-message {
        margin-bottom: 0px;
        border-radius: 0px;
        text-align: center;
        background-color: #789F73;
      }
      .alert-top-message h3{
        margin: 0 auto;
      }

      .modal-dialog {
        margin-top: 25%;
      }

{% block styles%}
{% endblock %}
      .background_img_thumb {
        width:100px;
        height:100px;
        background-image:url("{% static 'img/placeholder.svg' %}");
        background-size:cover;
        background-repeat:no-repeat;
        background-position: center;

      }

    </style>

<script type="text/javascript" src="https://js.stripe.com/v2/"></script>

</head>

<body>
  {% if marketing_message %}
  <div class="alert alert-top-message alert-dismissible" role="alert">
        <button id="marketing_message-btn" type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
    <div class="container">

      <h1>{{marketing_message.message|safe}}</h1>
    </div>
  </div>
  {% endif %}


{% include 'navbar.html' %}


  {% block jumbotron %}
  {% endblock %}


  <div class="container">
    {% if messages %}
      {% for message in messages %}
    <div class='alert {% if "success" in message.tags %}alert-success{% elif "warning" in message.tags %}alert-warning {% elif "error" in message.tags %}alert-danger {% endif %} alert-dismissible' role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
          {% if "safe" in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}  
    </div>
      {% endfor %}
    {% endif %}
      
  {% block content %}

  {% endblock content %}
</div>
{% include 'modal.html' %}


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://getbootstrap.com/docs/3.3/assets/js/ie-emulation-modes-warning.js"></script>


	<!-- Latest compiled and minified JavaScript -->
  <!-- Latest compiled and minified JavaScript -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>

  <script>
        $(document).ready(function(){
        $('#marketing_message-btn').click(function(){
            $.ajax({
              type: 'POST',
              url: '{% url "dismiss-marketing-message" %}',
              data: {
                'dismiss-marketing': true,
                'csrfmiddlewaretoken': '{{ csrf_token }}'
              },
              success: function(data){
                
              },
              error: function(){
                alert('Error! something went wrong, please try again later')
              }
            });
        });

        {% if not request.user.is_authenticated and not request.session.email_added_marketing and not 'accounts' in request.get_full_path %}
        function showModal(){
          $('#marketingModal').modal('show');
          // setTimeout(showModal, 5000);
        }
        // showModal()
        setTimeout(showModal, 2000);
            $('#sendMarketingForm').click(function(e){
              e.preventDefault()
              var mForm = $('#sendForm').serialize()
            $.ajax({
              type: 'POST',
              url: '{% url "ajax_email_signup" %}',
              data: mForm,
              success: function(data){
                $('#modalMessage').html('<p>' + data + '</p>')
                $('#marketingModal').modal('hide');
              },
              error: function(data){
                var obj = data.responseJSON
                $('#modalMessage').html('<p style="color:red;">' + obj.email + '</p>')


              },
            });
        });
        {% endif %}
    });

  </script>

  <script>
    $(document).ready(function(){
        {% block jquery %}{% endblock%}
    });
  </script>

  </body>
</html>

templates/products/checkout.html
{% extends 'base.html' %}

<script>
{% block jquery %}

	$(".shipping-label").click(function(){
		$('label').removeClass('shipping-label-selected');
		$(this).addClass('shipping-label-selected');
	});

	$(".billing-label").click(function(){
		$('label').removeClass('billing-label-selected');
		$(this).addClass('billing-label-selected');
	});

 	Stripe.setPublishableKey('{{ stripe_pub }}');

 	jQuery(function($){
 		$('#payment-form').submit(function(event){
 			var $form = $(this);

 			$form.find('button').prop('disabled', true);
 			Stripe.card.createToken($form, stripeResponseHandler);
 			return false;
 		});
 	});
 	function stripeResponseHandler(status, response) {
 		var $form = $('#payment-form');
 		if (response.error){
 			$('#card_errors_div').removeClass('hidden');
 			$form.find('.payment-errors').text(response.error.message);
 			$form.find('button').prop('disabled', false);
 		} else {
 			$('#card_errors_div').addClass('hidden');
 			var token = response.id; 
 			$form.append($('<input type"hidden" name"stripeToken"/>'));
 			$form.get(0).submit();
 		}
 	};

$('#addShippingAddress').click(function(e){
	e.preventDefault();
	$('#shippingAddressForm').fadeToggle();

});

	{% if not current_addresses %}
		$('#shippingAddressForm').fadeToggle();
	{% endif %}

{% endblock %}
</script>
<style>

{% block styles%}

.shipping-label{
	font-size: 16px;
	font-weight: normal;
	padding: 4px 25px;
	border: 1px solid #ccc;
	border-radius: 8px;
}
.shipping-label input[type=radio]{
	display: none;
}

.shipping-label:hover {
	font-size: 16px;
	font-weight: normal;
	background-color: #428bca;
	color: white;
	cursor: pointer;

}
.shipping-label-selected {
	font-size: 16px;
	font-weight: normal;
	background-color: #428bca;
	color: white;
	cursor: pointer;
}
.billing-label{
	font-size: 16px;
	font-weight: normal;
	padding: 4px 25px;
	border: 1px solid #ccc;
	border-radius: 8px;
}
.billing-label input[type=radio]{
	display: none;
}

.billing-label:hover {
	font-size: 16px;
	font-weight: normal;
	background-color: #428bca;
	color: white;
	cursor: pointer;

}
.billing-label-selected {
	font-size: 16px;
	font-weight: normal;
	background-color: #428bca;
	color: white;
	cursor: pointer;
}

@media(min-width: 1200px){
	.total{ position: fixed;
	 }
}

{% endblock %}
</style>

{% block content %}

<div class="col-sm-7 pull-right">
	<div class="total">
	<h3>Current total (VAT inc): {{ order.get_final_amount }}</h3>
<!-- 	<a href="#">Finalize checkout</a> -->
</div>
</div>

<div class="col-sm-9 pull-left">


<div class="col-sm-6 pull-right" id="shippingAddressForm" style="display:none;"> 
	<h3>Add new Shipping Address</h3>
	<form method="POST" action="{% url 'ajax-add-user-address' %}?next=checkout">{% csrf_token %}
		{{ address_form.as_p }}
	<input type="submit" class="btn btn-default" value="Add address"/>
	</form>
</div>




<form method="POST" action="" id="payment-form">{% csrf_token %}
{% if current_addresses %}
	
<div class="col-sm-12">
		<h3>Shipping Addresses</h3>
			{% for address in current_addresses %}
				
				{% if request.user.userdefaultaddress.shipping.id == address.id %}
					<label class="shipping-label shipping-label-selected">
						<input type="radio" name="Shipping_address", value="{{ address.id }}" checked="checked" /> {{ address.get_address }} <br/> 

						{% else %}
						<label class="shipping-label">
						<input type="radio" name="Shipping_address", value="{{ address.id }}"/> {{ address.get_address }}
				{% endif %}
					</label> <br/>
						 
			{% endfor %}
					</br>
<a href="{% url 'add-user-address' %}" id="addShippingAddress"> Add new address</a>
		
</div>
{% endif %}

	  {% if billing_addresses %}
	  <div class="col-sm-12">
		<h3>Billing Addresses</h3>
			

		{% for address in billing_addresses %}
		 
				{% if request.user.userdefaultaddress.billing.id == address.id %}
				<label class="billing-label billing-label-selected">
					<input type="radio" name="Billing_address", value="{{ address.id }}" checked="checked" /> {{ address.get_address }}  

					{% else %}
					<label class="billing-label"><br/>
					<input type="radio" name="Billing_address", value="{{ address.id }}"/> {{ address.get_address }} <br/>
						 
				{% endif %}
			</label>	

		{% endfor %}
			
	</div>
	{% endif %}

<div class="col-sm-6">
	<h3>Credit card Info</h3>

<div id="card_errors_div" class="alert alert-danger hidden payment-errors" role="alert">
</div>
	<div class="form-row">
		<div class="row">
		<div class="col-xs-6" style="padding-right: 0px;">
			<b>Card number</b>
			<input class="form-control" type="text" size="20" data-stripe="number"/>
		</div>
			<div class="col-xs-3">
				<b>CVC</b>
					<input class="form-control" type="text" size="4" data-stripe="cvc"/>
			</div>
		</div>
	</div>
</br>

		<div class="form-row">
			<b>Expiration (MM/YYYY)</b>
		<div class="row">
			<div class="col-xs-4" style="padding-right: 0px;">		
			<input class="form-control" type="text" size="2" data-stripe="exp-month" placeholder="e.g 02"/>
		</div>
		<div class="col-xs-6">
		<input class="form-control" type="text" size="4" data-stripe="exp-year" placeholder="e.g 2020"/>
		</div>
	</div>
	</div>

	</br>

	<button class="btn btn-default btn-lg" type="Submit">Submit Payment</button>
	
</div>
</form>
</div>
{% endblock %}

templates/products/modal.html
<div class="modal fade" id="marketingModal">
  <form method="POST" action="{% url 'ajax_email_signup' %}" id="sendForm">{% csrf_token %}
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title">Subscribe for latest fashion updates</h4>
      </div>
      <div class="modal-body">
        <!-- <input class="form-control" type="text" placeholder="Enter your email"/> -->
        <p id="modalMessage"></p>

        <input id="id_email" class="form-control" maxlength="200" type="email" name="email" placeholder="Enter your email">

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <input type="submit" class="btn btn-success" id="sendMarketingForm">
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
  </form>
</div><!-- /.modal -->

templates/products/navbar.html
    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}">Elsie Collections</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <!-- <li><a href="#about">About</a></li> -->
            <li><a href="#contact">Contact Us</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">What's up?<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
          </ul>
          <form class="navbar-form navbar-left" role="search" action="/s/">
            <div class="form-group">
               <input type="text" class="form-control" name="q" placeholder="Search Item">
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
          </form>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'items' %}">Products</a></li>
            <li><a href="{% url 'cart' %}">Cart <span class="badge">{% if not request.session.total_items %} 0 {% else %}{{ request.session.total_items }}{% endif %}</span></a></li>
            {% if user.is_authenticated %}
              <li><a href="#">Account</a></li>
              <li><a href="{% url 'auth_logout' %}">Logout</a></li>
            {% else %}
              <li><a href="{% url 'auth_login' %}">Login</a></li>
            {% endif %}

          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

templates/products/results.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<h1> Searched for: {{ query }}</h1>

{{ items }}

<table class="table">
	<thead>
		<th></th>
		<th>Item</th>
	</thead>

	<tbody>
		{% for item in items %}
		<tr>
			<td style="width: 160px; height: 160px;">
				{% if item.itemimage_set.all %}
				  {% for item in item.itemimage_set.all %}
                    {% if item.featured %}

<div style="width: 100%; height: 100%; background-image:url('{{ MEDIA_URL }}{{ item.image.url }}'); background-size:cover; background-repeat: no-repeat; background-position: center;"></div>

                    {% endif %}
                  {% endfor %}


				{% else %}
			<div style="width: 100%; height: 100%; background-image: url('{% static 'img/placeholder.svg' %}'); background-size:cover; background-repeat: no-repeat; background-position: center;"></div>
				{% endif %}
			</td>
			<td><a href="{{ item.get_absolute_url }}">{{ item }}</a></td>		
			
		</tr>
		{% endfor %}

	</tbody>

</table>

{% endblock %}

templates/products/single.html
{% extends 'base.html' %}

<div class="page-header">	
	<h1>{{ item.title }}</h1>
</div>
{% block content %}

<div class="row">
			<div class="col-sm-4">     
		     {% for image in images %}

		        {% if image.featured %}
		        <div class="col-xs-12">
		        <img class="img-responsive" src="{{ MEDIA_URL }}{{ image.image.url }}"/>
		        <hr/>
		        </div>
		        {% endif %}
		     {% endfor %}

		     {% for image in images %}

		       {% if not image.featured %}
		    <div class="col-xs-6">
		    	<a href="" class="thumbnail"></a>
		    	<img class="img-responsive" src="{{ MEDIA_URL }}{{ image.image.url }}">
		    </div>
		    {% endif %}
		    {% endfor %}
		  </div>
		  <div class="col-sm-8">
		    <div class="col-sm-8 pull-left">
            	<h1>{{ item.title }}
             		
            	</h1>
        	</div>
        		<div class="col-sm-4 pull-right">
	             	<form class="form pull-right" method="POST" action="{% url 'add-to-cart' item.slug %}">
	             		{% csrf_token %}
	             		<input class="btn btn-default btn-block" type="submit" value="Add to Cart"/>
	             		<input class="form-control" type="number" name="Qty" value="1"/>
	             
	             	{% if item.variation_set.all %}

	             		{% if item.variation_set.sizes %}
		             		<select class="form-control" name="size">
		             			{% for item in item.variation_set.sizes %}
		             				<option value="{{ item.title|lower }}">{{ item.title|capfirst }}</option>
		             			{% endfor %}
		             		</select>
	             		{% endif %}

		             	{% if item.variation_set.colors %}
		             		<select class="form-control" name="color">
		             			{% for item in item.variation_set.colors %}
		             				<option value="{{ item.title|lower }}">{{ item.title|capfirst }}</option>
		             			{% endfor %}	
		             		</select>
	             		{% endif %}

	             	{% endif %}   		
	             	</form>
             	</div>
             <div class="col-sm-12"></div>
	             <hr/>
	             Price: ${{ item.price }}<br/>
	             Shipping: Free with purchase above $100
	             <hr/>
             </div>
	             <div class="col-sm-12">
	             	{{ item.description|linebreaks }}
	             </div>

		    </div>	
</div>
{% endblock %}